# docker-compose.yml
version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: bookreview-mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bookreviewdb
      MYSQL_USER: appuser
      MYSQL_PASSWORD: secret
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
